config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions'
                                  # passwords: 'users/passwords'
  }
  root 'static_pages#home'
  get  '/home',   to: 'static_pages#home'
  get  '/term',   to: 'static_pages#term'
  get  '/edit_password', to: 'users#edit_password'
  patch  '/update_password', to: 'users#update_password'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts,         only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:new, :create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many   :likes, dependent: :destroy
  has_many   :iine_users, through: :likes, source: :user
  has_many   :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :picture, presence: true
  validate  :picture_size
  
  def give_iine(user)
    likes.create(user_id: user.id)
  end

  def cancel_iine(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def iine?(user)
    iine_users.include?(user)
  end

  private

    def picture_size
      if picture.size > 3.megabytes
        errors.add(:picture, "should be less than 3MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: :destroy
  
  def new
    @post = current_user.posts.build
  end
  
  def show
    @post = Post.find(params[:id])
    @comment_list = @post.comments
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to new_post_comment_path(@post)
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  private

    def post_params
      if params[:post]
        params.require(:post).permit(:picture)
      end
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <div class="row">
    <div class="user">
      <%= link_to gravatar_for(post.user, size: 50), post.user %>
      <%= link_to post.user.name, post.user %>
    </div>
    <div class="content">
      <% if post.picture? %>
        <%= link_to image_tag(post.picture.url), post_path(post), remote: true %>
      <% end %>
    </div>
    <div class="post_actionbar row">
      <div class="col-md-2">
        <%= render "likes/like", post: post %>
      </div>
      <div class="timestamp col-md-4">
        Posted <%= time_ago_in_words(post.created_at) %> ago.
      </div>
      <div class="col-md-offset-1 col-md-4">
        <% if current_user?(post.user) %>
          <%= link_to "削除", post, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
      </div>
    </div>
    <div class="comment_form">
      <%= form_for(@comment, url:post_comments_path(post)) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="col-md-8">
          <%= f.text_field :content, class: 'form-control' %>
        </div>
        <div class="col-md-2">
          <%= f.submit "コメント", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</li>

app/views/posts/_post_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <%= image_tag @post.picture.url %>
        <div>
          <% if @post.comments.any? %>
            <%= render 'shared/list_comment' %>
          <% else %>
            <%= render plain: "コメントはありません" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Post") %>
<h2>写真投稿</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3 jumbotron">
    <div class="post_form col-md-8 col-md-offset-2">
      <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
        </span>
        <%= f.submit "投稿する", class: "btn btn-primary submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.js.erb
$("#post-modal").html("<%= escape_javascript(render ('posts/post_modal')) %>")
$("#post-modal").modal("show")