config/routes.rb
Rails.application.routes.draw do

  get 'likes/create'
  get 'likes/destroy'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    sessions: 'users/sessions'
                                  # passwords: 'users/passwords'
  }
  root 'static_pages#home'
  get  '/home',   to: 'static_pages#home'
  get  '/term',   to: 'static_pages#term'
  get  '/edit_password', to: 'users#edit_password'
  patch  '/update_password', to: 'users#update_password'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts,         only: [:new, :show, :create, :destroy] do
    resources :comments, only: [:new, :create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to "UPLOAD", new_post_path, id: "upload" %>
    <% end %>
    <nav>
      <ul>
        <li><%= link_to "利用規約", term_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "picture app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "ユーザー", users_path %></li>
          <li><%= link_to "マイページ", current_user %></li>
          <li><%= link_to "設定", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>